repos:
  - repo: local
    hooks:
      - id: fmt-check
        name: fmt-check
        language: system
        entry: mise run fmt-check
        pass_filenames: false
      - id: lint
        name: lint
        language: system
        entry: mise run lint
        pass_filenames: false
